### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by jsheunis** [fladd/ScanSessionTool#10]
Ping: https://github.com/openjournals/joss-reviews/issues/6126

The JOSS checklist asks:

> Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

Installation instructions are clear, although I am unsure why `pipx` is used over `pip`, can you clarify?

Also, there are no explicitly stated dependencies. If there are none, it would would be good to state that.

**Comment by fladd** [comment]
Pipx mainly because it is an application only and not also a library, and it makes thing much easier for end users (no venv creation needed, readily available system command to run it, etc.). But using pip will work equally of course for those who prefer that.
Would you suggest to mention this explicitly?

Dependencies are pyyaml and pydicom, and that is indeed not stated anywhere (mainly, because the end user doesn't care, since pipx will take care of those automatically during installation). So from an end-user perspective, there are no dependencies that need fulfilling (on their side). I can be more explicit about this though and state that there are technical dependencies, but that the user does not need to take care of them themselves?

**Comment by jsheunis** [comment]
Thanks for the explanation. This makes sense.

I'm always a fan of making things explicit.

What i think could be a good idea is to create some separation between user docs and developer/contributor docs. I.e. for users, a more minimal set of instructions and dependencies can be provided, with the focus being getting the tool installed on their system and using it is as easily as possible.

For developers I think stating requirements explicitly (e.g. in `requirements.txt`), being able to install the package in a virtual environment, and making the package available via pip would be very beneficial. This relates to another issue: https://github.com/fladd/ScanSessionTool/issues/12

**Comment by fladd** [comment]
Yes, I can add the requirements.txt for developers to the repo.

Concerning installation via pip: That should be entirely possible. The package is on PyPi (that is also where pipx gets it from). Did you run into any issues installing with pip?

**Comment by jsheunis** [comment]
I didn't try installing via pip before making that comment. I did now, and all works well 👍
