### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jsheunis** [fladd/ScanSessionTool#13]
_Ping: https://github.com/openjournals/joss-reviews/issues/6126_

Some notes about testing:

1. I wanted to run/conduct any tests that the package includes, so I went to the location that seemed most intuitive for me ==> `./tests/`. There I found a readme that described the test setup. But this is not a foolproof way of telling people about testing. It could be made easier for developers/users to know what to do if they want to run tests. Especially developers need to know how to run tests if they're contributing code, so you can e.g. include a few notes on testing in the dev docs mentioned in https://github.com/fladd/ScanSessionTool/issues/12.
2. When following the testing steps, it's not obvious where exactly the protocol file (`ScanProtocol_TestData_sub-001_ses-007-Transfer_20211203.txt`) should be found. E.g. when I clicked "Open", the file browser on my system opened in a random location. I wasn't sure if the tool should automatically open the file browser in the package installation location, or whether the testing data was actually even installed together with the package. So I just cloned the git repo and navigated to the test protocol file in the local clone. But this wouldn't be obvious to someone who is unfamiliar with these systems. So some instructions would be good to improve user experience here.
3. The testing pipeline described in the mentioned readme feels almost more like a tutorial to me. I think this, or an adaptation of it, could actually be appropriate in the context of the walkthrough tutorial mentioned in https://github.com/fladd/ScanSessionTool/issues/11
4. I read the part about "Since Scan Session Tool is a graphical application, these tests have to be performed manually.", but I don't think the fact that it's a graphical application prevents the use of automated tests. I actually think the same tests can be automated, just without the clicking and visual verifying bits although these can be replaced with mock functions. And having automated tests (run via e.g. `pytest`) will allow: a) developers to run local tests to test their code contributions against, and b) you to set up continuous integration (via e.g. appveyor and/or github actions) so that tests can be run against new PRs. Both of these additions, automated testing and continuous integration, would improve the testing setup and the package itself substantially.

**Comment by fladd** [comment]
Thanks for the suggestions. 

1. We will include notes on testing in the dev docs.
2. We will be explicit that one has to navigate to the protocol file.
3. We did think about unit test intensively in the past and decided back then to not do it, due to all the difficulties involved in testing GUI functionality automatically. However, given your suggestion, we reviewed the possibilities again, and we will automatize part of our testing, where splitting logic from GUI is appropriate. In particular, we will automatize the archiving procedure (that is, the second part of the current testing procedure: loading of a protocol file and archiving based on the information in that). We decided, however, not to test the interaction of each element in the GUI (that is, the first part of the current testing procedure: loading/saving protocol files to/from information stored in GUI elements), as this functionality is inherently bound to user interaction.

**Comment by fladd** [comment]
After having spent (way too) many hours on this now, I eventually did add tests for both scan session protocol handling and data archiving! See main README.md for simple instructions on how to run.

**Note:**
Due to the way Scan Session Tool works and is implemented, I decided against separating the application logic from the GUI and testing it in isolation (because part of the core functionality of the proramme is closely tied to what can be seen on the screen; i.e. the scan session documentation). Running unit tests on GUI applications is not trivial and requires hacks to somehow intercept events into the main event loop from the outside. Common solutions for this (such as multithreading and asynchronious code (e.g. https://stackoverflow.com/questions/42295186/unittesting-a-tkinter-application, https://stackoverflow.com/questions/4083796/how-do-i-run-unittest-on-a-tkinter-app) did not work in this case. In the end, I had to implement part of the testing logic in the application itself, such that it can be triggered internally, based on how the application is started. This seems to work rather well I think!

I might, in the future, implement CI for this as well (have to read more into dummy displays for headless testing (e.g. https://arbitrary-but-fixed.net/2022/01/21/headless-gui-github-actions.html).
