### ISSUE TITLE
JOSS Paper comments

### ISSUE THREAD

**Issue by jsheunis** [fladd/ScanSessionTool#7]
_Ping: https://github.com/openjournals/joss-reviews/issues/6126_

On the whole, the paper is clearly written and explains the purpose and capability of the software tool concisely and intuitively.

Two comments:
- there is a typo in the last paragraph, line 40:
   > preporocessing
- the paper does not cover the "state of the field". From the reviewer checklist:
   > State of the field: Do the authors describe how this software compares to other commonly-used packages?
   A couple of sentences should be added to the paper to describe existing packages and how their functionality relate to the tool being described. I know, for example, of tools like [heudiconv](https://github.com/nipy/heudiconv) and the extended set of tools in the [ReproNim](https://github.com/ReproNim) world that operate in the same space. There are likely others too.

**Comment by fladd** [comment]
Thanks!

The "state of the field" requirement is an interesting one, as this is not part of the author checklist :-) I think this is also not covered in their example paper in the documentation: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography.

But I am of course happy to include a comparison to the two packages you mentioned. Finding related work was quite difficult (we tried before) actually, since we seem to use a different terminology (i.e. searching for "MRI scan session documentation" didn't really result in anything useful).

**Comment by jsheunis** [comment]
Interesting. Good feedback for JOSS then ;) However, I think it's definitely a good idea to include something like "state of the field" in such a paper, as it provides useful context for the reader or potential user.

Re the specific tools I shared, I only know of them through my own involvement in related projects, and their popularity in the open neuroimaging community, but I'm sure others exist. Just as I'm sure it will be difficult to find them :)

**Comment by fladd** [comment]
Thanks again, we have implemented these suggestions now.
